version: '3.4'
services:
  app: &app_base
    image: hammer_app_development
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    command: bundle exec rails server -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
