version: '3.4'
services:
  app: &app_base
    build: hammer_app_production
      context: .
      args:
        - BUNDLE_WITHOUT=development:test
        - EXECJS_RUNTIME=Disabled
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - RAILS_ENV=production
        - RAILS_LOG_TO_STDOUT=true
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - RAILS_SERVE_STATIC_FILES=true
        - NODE_ENV=production
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    command: bundle exec rails server -b '0.0.0.0'
    ports:
      - "3000:3000"
    restart: always
