version: '3.7'
services:
  mongodb:
    image: mongo:4.0.6
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - /data/db:/data/db
    networks:
      - hammer-backend

  hammer-app:
    image: hammer_app_production
    container_name: hammer-app
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=development:test
        - EXECJS_RUNTIME=Disabled
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - NODE_ENV=production
        - RAILS_ENV=production
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      - APP_HOST=hammer.redapt.com
      - APP_PORT
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_HOST_PORT=${DB_HOST}:${DB_PORT}
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_SSL=${DB_SSL}
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SMTP_AUTHENTICATION=plain
      - SMTP_DOMAIN=hammer.redapt.com
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=587
      - SMTP_SERVER=smtp.sendgrid.net
      - SMTP_USERNAME=${SMTP_USERNAME}
      - VIRTUAL_HOST=hammer.redapt.com
      - LETSENCRYPT_HOST=hammer.redapt.com
      - LETSENCRYPT_EMAIL=cplain@attunix.com
    restart: always
    volumes:
      - type: tmpfs
        target: /app/tmp/pids/
    networks:
      - hammer-frontend
      - hammer-backend

networks:
  hammer-frontend:
    name: hammer-frontend
  hammer-backend:
    name: hammer-backend
