version: '3.4'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: mongo:4.0.6
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - /data/db:/data/db

  app:
    image: hammer_app_development
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs
        - EXECJS_RUNTIME=Node
        - NODE_ENV=development
        - RAILS_ENV=development
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      - APP_HOST=localhost
      - APP_PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_HOST_PORT=${DB_HOST}:${DB_PORT}
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SMTP_AUTHENTICATION=plain
      - SMTP_DOMAIN=hammer.redapt.com
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=587
      - SMTP_SERVER=smtp.sendgrid.net
      - SMTP_USERNAME=${SMTP_USERNAME}
      - VIRTUAL_HOST=test.domain.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
