version: '3.4'
services:
  app:
    build: hammer_app_production
      context: .
      args:
        - BUNDLE_WITHOUT=development:test
        - EXECJS_RUNTIME=Disabled
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - NODE_ENV=production
        - RAILS_ENV=production
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      - DB_HOST=hammer-dev-mongodb.documents.azure.com:10255
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    restart: always
