version: '3.4'
services:
  db:
    image: mongo:4.0.6
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - /data/db:/data/db

  app:
    image: hammer_app_production
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=development:test
        - EXECJS_RUNTIME=Disabled
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - NODE_ENV=production
        - RAILS_ENV=production
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      - APP_HOST=hammer.westus.cloudapp.azure.com
      - APP_PORT
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_HOST_PORT=${DB_HOST}:${DB_PORT}
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_SSL=${DB_SSL}
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SMTP_AUTHENTICATION=plain
      - SMTP_DOMAIN=hammer.redapt.com
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=587
      - SMTP_SERVER=smtp.sendgrid.net
      - SMTP_USERNAME=${SMTP_USERNAME}
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - type: tmpfs
        target: /app/tmp/pids/
